"""AES-256-GCM encryption for tezit bundles.

Provides symmetric encryption/decryption using AES-256-GCM, which gives
both confidentiality and authenticity. Each file is encrypted with a
unique nonce (96-bit, randomly generated by AESGCM). The same 256-bit
key is used for all files in a single tezit bundle.

Key lifecycle:
    1. generate_key() at tez_build time -- one key per tezit.
    2. key_to_b64() to transmit the key to the relay for escrow.
    3. b64_to_key() on the recipient side to recover the key.
    4. encrypt_file() / decrypt_file() for per-file operations.

Dependencies:
    cryptography >= 41.0  (hazmat AESGCM)
"""

from __future__ import annotations

import base64
import os
from typing import TYPE_CHECKING

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

if TYPE_CHECKING:
    pass

# AES-256 requires a 32-byte (256-bit) key.
_KEY_LENGTH_BYTES = 32

# AESGCM uses a 96-bit (12-byte) nonce by convention.
_NONCE_LENGTH_BYTES = 12


def generate_key() -> bytes:
    """Generate a random 256-bit AES key.

    Uses ``os.urandom`` via the ``cryptography`` library's AESGCM key
    generation, which is equivalent to ``os.urandom(32)`` but makes
    the intent explicit.

    Returns:
        A 32-byte random key suitable for AES-256-GCM.
    """
    return AESGCM.generate_key(bit_length=256)


def encrypt_file(
    plaintext: bytes,
    key: bytes,
) -> tuple[bytes, bytes, bytes]:
    """Encrypt data using AES-256-GCM.

    A fresh random nonce is generated for each call, so calling this
    function twice with the same plaintext and key will produce
    different ciphertext.

    The ``cryptography`` library appends the 16-byte GCM authentication
    tag to the ciphertext. This function splits them apart so they can
    be stored/transmitted independently.

    Args:
        plaintext: The raw file bytes to encrypt.
        key: A 32-byte AES-256 key (from ``generate_key``).

    Returns:
        A tuple of ``(ciphertext, nonce, tag)`` where:
        - ``ciphertext`` is the encrypted data (same length as plaintext).
        - ``nonce`` is the 12-byte nonce used for this encryption.
        - ``tag`` is the 16-byte GCM authentication tag.

    Raises:
        ValueError: If the key is not 32 bytes.
    """
    _validate_key(key)
    nonce = os.urandom(_NONCE_LENGTH_BYTES)
    aesgcm = AESGCM(key)

    # AESGCM.encrypt returns ciphertext || tag (16 bytes appended).
    ct_with_tag = aesgcm.encrypt(nonce, plaintext, associated_data=None)

    # Split: last 16 bytes are the GCM tag.
    ciphertext = ct_with_tag[:-16]
    tag = ct_with_tag[-16:]

    return ciphertext, nonce, tag


def decrypt_file(
    ciphertext: bytes,
    key: bytes,
    nonce: bytes,
    tag: bytes,
) -> bytes:
    """Decrypt data using AES-256-GCM.

    Reconstructs the ``ciphertext || tag`` format expected by the
    ``cryptography`` library and decrypts. Raises on authentication
    failure (tampered data or wrong key).

    Args:
        ciphertext: The encrypted data bytes.
        key: The 32-byte AES-256 key used for encryption.
        nonce: The 12-byte nonce used during encryption.
        tag: The 16-byte GCM authentication tag.

    Returns:
        The original plaintext bytes.

    Raises:
        ValueError: If the key is not 32 bytes.
        cryptography.exceptions.InvalidTag: If authentication fails
            (wrong key, corrupted data, or tampered ciphertext/tag).
    """
    _validate_key(key)
    aesgcm = AESGCM(key)

    # Reassemble the ciphertext || tag format.
    ct_with_tag = ciphertext + tag

    return aesgcm.decrypt(nonce, ct_with_tag, associated_data=None)


# ------------------------------------------------------------------
# Base64 key serialisation (for relay transmission)
# ------------------------------------------------------------------


def key_to_b64(key: bytes) -> str:
    """Encode a binary AES key as a URL-safe base64 string.

    Used when transmitting the key to the relay server or storing
    it in metadata. The encoding is URL-safe (``+/`` replaced with
    ``-_``) and padding is preserved for unambiguous decoding.

    Args:
        key: A 32-byte AES-256 key.

    Returns:
        A base64url-encoded string (44 characters with padding).

    Raises:
        ValueError: If the key is not 32 bytes.
    """
    _validate_key(key)
    return base64.urlsafe_b64encode(key).decode("ascii")


def b64_to_key(b64: str) -> bytes:
    """Decode a URL-safe base64 string back to a binary AES key.

    Args:
        b64: A base64url-encoded key string (from ``key_to_b64``).

    Returns:
        The 32-byte AES-256 key.

    Raises:
        ValueError: If the decoded key is not 32 bytes or the
            base64 string is malformed.
    """
    try:
        key = base64.urlsafe_b64decode(b64)
    except Exception as exc:
        msg = f"Invalid base64 key string: {exc}"
        raise ValueError(msg) from exc

    if len(key) != _KEY_LENGTH_BYTES:
        msg = f"Decoded key is {len(key)} bytes, expected {_KEY_LENGTH_BYTES}"
        raise ValueError(msg)

    return key


# ------------------------------------------------------------------
# Internal helpers
# ------------------------------------------------------------------


def _validate_key(key: bytes) -> None:
    """Raise ValueError if the key is not exactly 32 bytes."""
    if not isinstance(key, bytes):
        msg = f"Key must be bytes, got {type(key).__name__}"
        raise ValueError(msg)
    if len(key) != _KEY_LENGTH_BYTES:
        msg = f"Key must be {_KEY_LENGTH_BYTES} bytes, got {len(key)}"
        raise ValueError(msg)
